'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {loadDashboardData,type DashboardData} from '@/lib/dashboard-data';
import {LogoutButton} from '@/components/LogoutButton';
const number=(value:number|null,fallback='Aguardando dados')=>value===null?fallback:new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value);
const money=(value:number|null,fallback='Aguardando atualização')=>value===null?fallback:new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:2}).format(value);
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR').format(new Date(value+'T12:00:00')):'Aguardando primeira atualização';
const statusLabel={DENTRO_DO_PLANO:'Dentro do plano',ATENCAO:'Atenção',CRITICO:'Crítico'} as const;
function Metric({title,value,suffix,accent=false}:{title:string;value:string;suffix:string;accent?:boolean}){const waiting=value.startsWith('Aguardando');return <div className={'metric '+(accent?'accent':'')}><span>{title}</span><strong>{value}</strong><small>{suffix}</small><div className="track"><i style={{width:waiting?'0%':'82%'}}/></div></div>}
export default function Home(){
 const [director,setDirector]=useState(false),[data,setData]=useState<DashboardData|null>(null);
 useEffect(()=>{void loadDashboardData().then(setData)},[]);
 if(!data)return <div className="login-page"><div className="login-card"><span className="eyebrow">SBON 17B</span><h1>Carregando painel…</h1></div></div>;
 const projectionRatio=data.target&&data.annualProjection?Math.min(100,data.annualProjection/data.target*100):0;
 const deviationText=data.deviation===null?'Aguardando dados':new Intl.NumberFormat('pt-BR',{style:'percent',minimumFractionDigits:1,maximumFractionDigits:1}).format(data.deviation/100);
 const sparks=data.weeklyExecuted.length?data.weeklyExecuted.map(v=>{const min=Math.min(...data.weeklyExecuted),max=Math.max(...data.weeklyExecuted);return max===min?50:25+(v-min)/(max-min)*60}):[];
 return <div className={'app '+(director?'director':'')}><header className="topbar"><div className="brand"><span className="mark">V</span><span><b>vitalux</b><small>ECOATIVA</small></span></div><nav><Link className="active" href="/">Dashboard</Link><Link href="/analise">Análise</Link><Link href="/atualizar">Atualizar</Link><Link href="/historico">Histórico</Link></nav><div className="header-actions"><span className="updated">Atualizado em <b>{date(data.latestDate)}</b></span><button onClick={()=>setDirector(!director)}>{director?'Sair do modo':'Modo Diretoria'}</button><LogoutButton/><span className="avatar" aria-label="Usuário">●</span></div></header>
 <main><section className="intro"><div><span className="eyebrow">PAINEL EXECUTIVO</span><h1>SBON 17B</h1><p>Visão consolidada de desempenho do contrato{data.source==='demo'?' · Demonstração local':''}</p></div><div className="status"><i/> {data.status?statusLabel[data.status]:'Projeção em formação'}</div></section>
 <section className="kpis">{[['Valor do contrato',money(data.contractValue,'Aguardando definição'),'Contrato consolidado'],['Faturado no ano',money(data.billingYtd),'Competências do exercício'],['Meta anual',data.target===null?'Aguardando definição':number(data.target)+' economias','Exercício atual'],['Projeção anual',data.annualProjection===null?'Projeção em formação':number(data.annualProjection)+' economias',data.target&&data.annualProjection?projectionRatio.toFixed(1).replace('.',',')+'% da meta':'Aguardando dados']].map(([label,value,note])=><article className="kpi" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
 <section className="grid"><article className="panel"><Head no="01" title="Tendência da meta" extra={<span className="pill">{data.status?statusLabel[data.status].toUpperCase():'EM FORMAÇÃO'}</span>}/><div className="deviation"><div><span>Desvio projetado</span><strong>{deviationText}</strong><small>{data.deviation===null?'Mínimo de 2 deltas válidos':''}</small></div><div className="spark">{sparks.map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="compare"><span>Meta <b>{number(data.target)}</b></span><div className="track"><i style={{width:projectionRatio+'%'}}/></div><span>Projeção <b>{number(data.annualProjection)}</b></span></div></article>
 <article className="panel"><Head no="02" title="Origem do desvio" extra={<Link href="/analise">Ver análise →</Link>}/><p className="hint">Distribuição do déficit físico acumulado até a data</p>{data.origin?.engineeringPercent===null?<p>Sem desvio relevante</p>:data.origin?<div className="origin"><Bar label="Engenharia" percent={data.origin.engineeringPercent??0} note={number(Math.round(data.origin.engineering))+' economias'}/><Bar label="Execução" percent={data.origin.executionPercent??0} note={number(Math.round(data.origin.execution))+' economias'} orange/></div>:<p>Aguardando dados</p>}</article></section>
 <section className="grid"><article className="panel"><Head no="03" title="Entrega da engenharia" extra={<span className="date">{data.latestDate?date(data.latestDate):''}</span>}/><div className="metrics"><Metric title="Economias" value={number(data.available,'Aguardando atualização')} suffix="disponíveis para ligação"/><Metric title="Rede" value={data.networkApproved===null?'Aguardando atualização':number(data.networkApproved)+' m'} suffix="aprovados para execução"/></div></article><article className="panel"><Head no="04" title="Execução real" extra={<span className="date orange">{data.latestDate?date(data.latestDate):''}</span>}/><div className="metrics"><Metric title="Economias" value={number(data.executed,'Aguardando atualização')} suffix="executadas" accent/><Metric title="Rede" value={data.networkExecuted===null?'Aguardando atualização':number(data.networkExecuted)+' m'} suffix="executados" accent/></div></article></section>
 {!director&&data.openActions>0&&<section className="actions"><div><span>!</span><div><b>{data.openActions} ações em aberto</b><small>Acompanhamento requerido</small></div></div><Link href="/acoes">Acompanhar ações →</Link></section>}</main><footer><span>SBON 17B · Vitalux Ecoativa</span><span>Desenvolvido por Lurian Hackenhaar</span></footer></div>
}
function Head({no,title,extra}:{no:string;title:string;extra:React.ReactNode}){return <div className="panel-head"><div><span>{no}</span><h2>{title}</h2></div>{extra}</div>}
function Bar({label,percent,note,orange=false}:{label:string;percent:number;note:string;orange?:boolean}){return <div className={orange?'bar orange':'bar'}><span>{label} <b>{percent.toFixed(0)}%</b></span><div className="track"><i style={{width:percent+'%'}}/></div><small>{note}</small></div>}
